version: '3.7'

services:
  springbootapp:
    image: eya115/gestionski:1.0.0
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SERVLET_CONTEXT_PATH: /api
      SERVER_PORT: 8089
      SPRING_MVC_FORMAT_DATE: yyyy-MM-dd
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: stationSki
    volumes:
      - dbdata:/var/lib/mysql
#each service is a docker-compose.yml
  prometheus:
    image: prom/prometheus
    container_name: prometheusContainer
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafanacontainer
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  dbdata:
