global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'springbootapp'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['g3-devops-pipeline-eya-springbootapp-1:8089']

